version: '3.1'

services:
 
 beaconprod:
    build:
      context: .
    container_name: beaconprod
    ports:
      - "5070:5070"
    entrypoint: ['python','-m','beacon']
    volumes:
      - ./beacon/logs/logs.log:/beacon/logs/logs.log
      - ./beacon/conf/conf.py:/beacon/conf/conf.py